### PR TITLE
Fix umbrella test count

### PR DESCRIPTION
**Pull request by luc-tielen**

### CODE REVIEW

**Comment by luc-tielen** [comment]
Fixes #33.

Looks like tests in CI build fail because of following reason:
** (UndefinedFunctionError) undefined function: MapSet.new/1
when doing mix deps.get (package jsx)

(But when running locally they are fine for me.)
@parroty or  @myronmarston can you re-run/verify manually?

**Comment by luc-tielen** [comment]
So, any updates on this @parroty? Been almost a week now.
If the build failure is a problem, it's an error in hex for Elixir version 1.1.1, due to MapSet.new not being available there.
Maybe a separate issue should be created to fix it (and potentially add other more recent versions of Elixir too.)

**Comment by parroty** [comment]
Thanks and very sorry taking time to merge.

**Comment by luc-tielen** [comment]
No problem, glad it got merged in :)

**Pull request merged**
