### PR TITLE
Added possibility to specify amount of tests in config

### PR DESCRIPTION
**Pull request by Primordus**

### CODE REVIEW

**Comment by parroty** [comment]
Thanks, it sounds nice. Just confirmation, but can I understand it's independent from #12? (can be separately merged?)

**Comment by Primordus** [comment]
Yes, this is something completely different :) I wanted the option to specify how many tests are being ran each time (per environment). I just tried merging both PR's onto master, there is a slight merge conflict in the README but no problems in the code itself. (README should contain updates from both branches, easy fix).

**Comment by parroty** [comment]
Thanks!

**Comment by parroty** [comment]
I just realized this setting doesn't work for `ExCheck.check(module_name)` and found https://github.com/krestenkrab/triq/pull/54 along with it. 
Before it gets merged, I am thinking to add a conditional logic to use `:triq.module` as above (does it make sense?)

**Comment by Primordus** [comment]
Ah I should've mentioned that.. I would keep logic the way it is since no errors will happen (just wrong amount of tests), hopefully krestenkrab accepts that small pull request soon and then everything will be streamlined and work as intended again.

**Comment by parroty** [comment]
OK. At the moment, I'll just put reference in the readme to this issue item and wait for the merge (and then revisit sometime later. Need to upgrade the dependency anyway).

**Comment by Primordus** [comment]
krestenkrab/triq#54 has been merged in! This pull request should now work with triq:module/2 too. :smiley:

**Comment by parroty** [comment]
Nice :+1:

**Pull request merged**
